### PR TITLE
July issue v6

### LINKED ISSUE #709: Do we need import, new, export to CSV and three-dot actions in check-in detail view
**Describe the bug**
Do we need import, new, export to CSV and three-dot actions in check-in detail view 

**To Reproduce**
1. Go to the event detail view
2. Go to check-in page from three dots 
3. Check the check in page

### LINKED ISSUE #796: Sponsor :- Max 2 sponsors are deleted even if more than 2 are selected
-Login to event app
-Create a new event and  to to the event details page and add more than 2 sponsors or go to the event details page of any event with more than 2 sponsors added
-Scroll down to the sponsor grid
-Select more than 2 sponsors to delete
1)its deletes max 2 sponsors at a time
2)change the delete alert accordingly for plural deletes
https://www.loom.com/share/5b86012ad7ec409b86ed62fcb9cbd62a

### LINKED ISSUE #934: Checkin>> not able to add attendees from check in page
**Describe the bug**
when we add attendee from check in page its not getting added in grid 

**To Reproduce**
1. Go to event app
2. go to event 
3. go to check in 
4. add attendee
5. see the record

**Expected behavior**
record should display attendees when we add  attendee on check in screen

**Screenshots**
I
image

### PR DESCRIPTION
**Pull request by rishi9684**
#843 Resolved
#934 Resolved
#709 Resolved
#796 bug solved again
#855 Resolved

### CODE REVIEW

File: config/templates/grids/eventSponsor-grid/actions/row-select/delete-item.vue [hunk 1]
```diff
@@ -71,10 +71,16 @@ export default {
...
         if (getEvent) {
           const contacts = getEvent.contactlist
-          this.items.map((e) => {
-            contacts.pop(e)
+          const selectedList = this.items.map((e) => {
+            return e.id
           })
-          this.deleteItems(contacts)
+          const finalContacts = []
+          contacts.map((e) => {
```
Comment (SukantGujar) [inline config/templates/grids/eventSponsor-grid/actions/row-select/delete-item.vue:78]: You should use filter instead of map

**Review by SukantGujar — CHANGES_REQUESTED** [review]

**Review by SukantGujar — APPROVED** [review]
