### PR TITLE
May issue 432

### LINKED ISSUE #635: Venue Name is not displayed in the the event address on the registration site and email
-Login to the event app
-create an event with Venue and add the "Venue Name" and all other details->save->create the event
-GO to the registration site and check the complete address-->"Venue name " not displayed
highlighted "Kidscommom " is the venue name which is not visible on the registration site
image
image

### LINKED ISSUE #685: Getting white bar at bottom while loading event tiles in black theme
**Describe the bug**
Getting white bar at bottom while loading event tiles in black theme

**To Reproduce**
1. Go to event tile view
2. make black theme on 
3. reload and check

### PR DESCRIPTION
**Pull request by rishi9684**
#432 Resolved
#635 Resolved
#685 Resolved

### CODE REVIEW

File: components/common/theme/index.vue [hunk 1]
```diff
@@ -6,7 +6,33 @@
...
+<script>
+export default {
+  props: {
+    attrs: {
+      type: Object,
+      default: () => ({}),
+    },
+  },
+  mounted() {
+    const theme = localStorage.getItem('darkTheme')
```
Comment (SukantGujar) [inline components/common/theme/index.vue:23]: Prepend the userid to the key name.

**Review by SukantGujar — CHANGES_REQUESTED** [review]

File: components/common/theme/index.vue (hunk 1 above)
Comment (rishi9684) [reply components/common/theme/index.vue]: added prefix as hashid

**Review by SukantGujar — APPROVED** [review]
